choshinav/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exable.urls')),
]

exable/urls.py
from django.urls import path
from . import views

app_name = 'exable'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:memo_id>', views.detail, name='detail'),
    path('new_memo', views.new_memo, name='new_memo'),
    path('delete_memo/<int:memo_id>', views.delete_memo, name='delete_memo'),
    path('edit_memo/<int:memo_id>', views.edit_memo, name='edit_memo'),
]

exable/models.py
from django.db import models

class Memo(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

exable/forms.py
from django.forms import ModelForm
from .models import Memo

class MemoForm(ModelForm):
    class Meta:
        model = Memo
        fields = ['title', 'text']

exable/views.py
from .models import Memo
from django.shortcuts import get_object_or_404
from .forms import MemoForm
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

def new_memo(request):
    if request.method == "POST":
        form = MemoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('exable:index')
    else:   
        form = MemoForm
    return render(request, 'exable/new_memo.html', {'form': form })

def index(request):
  memos = Memo.objects.all().order_by('-updated_datetime')
  return render(request, 'exable/index.html', { 'memos': memos })

def detail(request, memo_id):
  memo = get_object_or_404(Memo, id=memo_id)
  return render(request, 'exable/detail.html', {'memo': memo})

@require_POST
def delete_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    memo.delete()
    return redirect('exable:index')

def edit_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    if request.method == "POST":
        form = MemoForm(request.POST, instance=memo)
        if form.is_valid():
            form.save()
            return redirect('exable:index')
    else:
        form = MemoForm(instance=memo)
    return render(request, 'exable/edit_memo.html', {'form': form, 'memo':memo })

exable/templates/exable/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <title>DjangoBrosMemo</title>
  <link rel="stylesheet" type="text/css" href="{% static 'exable/css/style.css' %}">
</head>

<body>
  <h1>DjangoBrosMemo</h1>

  <div class="container">
    {% block content %}{% endblock %}
  </div>

</body>
</html>

exable/templates/exable/detail.html
<div>
    <a href="{% url 'exable:index' %}">ホームに戻る</a>
  </div>
  
  <h2>{{ memo.title }}</h2>
  <div>
    {{ memo.text | linebreaks | urlize }}
  </div>

  <button><a class="btn" href="{% url 'exable:edit_memo' memo.pk %}">編集</a></button>

  <form method="post" action="{% url 'exable:delete_memo' memo.pk %}">{% csrf_token %}
    <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
  </form>

exable/templates/exable/edit_memo.html
<div>
  <a href="{% url 'exable:detail' memo.id %}">戻る</a>
  </div>
  
  <form action="{% url 'exable:edit_memo' memo.id %}" method="POST">{% csrf_token %}
    <table>
      <tr>
        <th>タイトル</th>
        <td>{{ form.title }}</td>
      </tr>
      <tr>
        <th>テキスト</th>
        <td>{{ form.text }}</td>
      </tr>
    </table>
    <button class="btn" type="submit">保存</button>
  </form>

exable/templates/exable/index.html
{% extends 'exable/base.html' %}

{% block content %}

    <a class="btn" href="{% url 'exable:new_memo' %}">新規メモ作成</a>

    {% for memo in memos %}
    <a href="{% url 'exable:detail' memo.id %}" class="memo-title">
    <div>
        {{ memo }}
        <span class="updated_datetime">{{ memo.updated_datetime }}</span>
    </div>
    </a>
    {% endfor %}

{% endblock %}

exable/templates/exable/new_memo.html
<div>
    <a href="{% url 'exable:index' %}">ホームに戻る</a>
  </div>
  
  <form action="{% url 'exable:new_memo' %}" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">保存</button>
  </form>